version: '3.9'

services:
  mongo:
    image: mongo
    volumes:
      - ./mongo:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_HOST: localhost
  
  server:
    build: ./server
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      MONGODB_HOST: mongodb://mongo
      MONGODB_PORT: 27017
      MONGO_USER: server
      MONGO_PASSWORD: password
      PORT: 5000

volumes:
  mongo: