apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: mongo-claim
  name: mongo-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
