apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    service: server-ingress
  name: server-ingress
  namespace: default
spec:
  defaultBackend:
    service:
      name: server-service
      port:
        number: 5000
  rules:
  - host: izzu.me