apiVersion: v1
kind: Service
metadata:
  labels:
    service: server-exposer
  name: server-exposer
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    service: server
  type: LoadBalancer
  loadBalancerIP: 34.88.87.125 # TODO: Make it a secret