---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "server-ingress"
  namespace: "default"
  annotations:
    networking.gke.io/managed-certificates: "lindria-ssl"
    nginx.ingress.kubernetes.io/health-check-path: /healthz
spec:
  defaultBackend:
    service:
      name: "server-service"
      port:
        number: 5000
  rules:
  - host: lindria.com
    http:
      paths:
      - path: /
        backend:
          service:
            name: "server-service"
            port:
              number: 5000